In [14]:
import numpy as np
import pandas as pd

df = pd.read_csv('spotify-tracks-dataset.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [15]:
df = df.drop(columns=['Unnamed: 0.1','Unnamed: 0'])
df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [16]:
df.shape

(114000, 20)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          114000 non-null  str
 1   artists           113999 non-null  str
 2   album_name        113999 non-null  str
 3   track_name        113999 non-null  str
 4   popularity        114000 non-null  int64
 5   duration_ms       114000 non-null  int64
 6   explicit          114000 non-null  bool
 7   danceability      114000 non-null  float64
 8   energy            114000 non-null  float64
 9   key               114000 non-null  int64
 10  loudness          114000 non-null  float64
 11  mode              114000 non-null  int64
 12  speechiness       114000 non-null  float64
 13  acousticness      114000 non-null  float64
 14  instrumentalness  114000 non-null  float64
 15  liveness          114000 non-null  float64
 16  valence           114000 non-null  float64
 17  tempo             114000 non-null  float64
 18  time_signature    114000 non-null  int64
 19  track_genre       114000 non-null  str
dtypes: bool(1), float64(9), int64(5), str(5)
memory usage: 25.9 MB

In [18]:
df['track_id'] = df['track_id'].astype('string')
df['artists'] = df['artists'].astype('string')
df['album_name'] = df['album_name'].astype('string')
df['track_name'] = df['track_name'].astype('string')
df['track_genre'] = df['track_genre'].astype('string')

df = df.dropna()

df.info()

<class 'pandas.DataFrame'>
Index: 113999 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          113999 non-null  string
 1   artists           113999 non-null  string
 2   album_name        113999 non-null  string
 3   track_name        113999 non-null  string
 4   popularity        113999 non-null  int64
 5   duration_ms       113999 non-null  int64
 6   explicit          113999 non-null  bool
 7   danceability      113999 non-null  float64
 8   energy            113999 non-null  float64
 9   key               113999 non-null  int64
 10  loudness          113999 non-null  float64
 11  mode              113999 non-null  int64
 12  speechiness       113999 non-null  float64
 13  acousticness      113999 non-null  float64
 14  instrumentalness  113999 non-null  float64
 15  liveness          113999 non-null  float64
 16  valence           113999 non-null  float64
 17  tempo             113999 non-null  float64
 18  time_signature    113999 non-null  int64
 19  track_genre       113999 non-null  string
dtypes: bool(1), float64(9), int64(5), string(5)
memory usage: 26.8 MB

In [19]:
df.duplicated().sum()

np.int64(450)

In [20]:
df = df.drop_duplicates(subset=['track_name', 'artists'], keep='first')

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df = df.drop(columns=['track_id','artists','album_name','track_name'])
df.head()

,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [23]:
df['track_genre'].nunique()

113

In [24]:
df['explicit'] = df['explicit'].astype(int)

In [25]:
df_cleaned = df
df_cleaned.head(20)

,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,73,230666,0,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,55,149610,0,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,57,210826,0,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,71,201933,0,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,82,198853,0,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
5,58,214240,0,0.688,0.4810,6,-8.807,1,0.1050,0.2890,0.000000,0.1890,0.6660,98.017,4,acoustic
6,74,229400,0,0.407,0.1470,2,-8.822,1,0.0355,0.8570,0.000003,0.0913,0.0765,141.284,3,acoustic
7,80,242946,0,0.703,0.4440,11,-9.331,1,0.0417,0.5590,0.000000,0.0973,0.7120,150.960,4,acoustic
8,74,189613,0,0.625,0.4140,0,-8.700,1,0.0369,0.2940,0.000000,0.1510,0.6690,130.088,4,acoustic
9,56,205594,0,0.442,0.6320,1,-6.770,1,0.0295,0.4260,0.004190,0.0735,0.1960,78.899,4,acoustic
10,74,244800,0,0.627,0.3630,8,-8.127,1,0.0291,0.2790,0.000000,0.0928,0.3010,99.905,4,acoustic
11,69,240165,0,0.483,0.3030,4,-10.058,1,0.0429,0.6940,0.000000,0.1150,0.1390,133.406,3,acoustic
12,52,198712,0,0.489,0.3140,7,-9.245,0,0.0331,0.7490,0.000000,0.1130,0.6070,124.234,4,acoustic
13,62,248448,0,0.691,0.2340,3,-6.441,1,0.0285,0.7770,0.000000,0.1200,0.2090,87.103,4,acoustic
14,56,188133,0,0.755,0.7800,2,-6.084,1,0.0327,0.1240,0.000028,0.1210,0.3870,120.004,4,acoustic
15,58,244986,0,0.489,0.5610,4,-7.933,1,0.0274,0.2000,0.000046,0.1790,0.2380,83.457,3,acoustic
16,56,129750,0,0.706,0.1120,2,-18.098,1,0.0391,0.8270,0.000004,0.1250,0.4140,110.154,4,acoustic
17,54,169728,0,0.795,0.0841,10,-18.090,0,0.0461,0.7420,0.000012,0.0853,0.6090,91.803,4,acoustic
19,67,260186,0,0.717,0.3200,3,-8.393,1,0.0283,0.8300,0.000000,0.1070,0.3220,107.946,4,acoustic
21,63,174174,0,0.678,0.3510,0,-8.654,1,0.0266,0.7470,0.000000,0.3550,0.5690,90.032,4,acoustic

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 81343 entries, 0 to 113999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   popularity        81343 non-null  int64
 1   duration_ms       81343 non-null  int64
 2   explicit          81343 non-null  int64
 3   danceability      81343 non-null  float64
 4   energy            81343 non-null  float64
 5   key               81343 non-null  int64
 6   loudness          81343 non-null  float64
 7   mode              81343 non-null  int64
 8   speechiness       81343 non-null  float64
 9   acousticness      81343 non-null  float64
 10  instrumentalness  81343 non-null  float64
 11  liveness          81343 non-null  float64
 12  valence           81343 non-null  float64
 13  tempo             81343 non-null  float64
 14  time_signature    81343 non-null  int64
 15  track_genre       81343 non-null  string
dtypes: float64(9), int64(6), string(1)
memory usage: 11.1 MB

In [27]:
def mood_label(df):
    valence = df['valence'].median()
    energy = df['energy'].median()
    print(f"Threshold Valence: {valence:.4f}")
    print(f"Threshold Energy: {energy:.4f}\n")

mood_label(df_cleaned)

Threshold Valence: 0.4490
Threshold Energy: 0.6780

In [28]:
import seaborn as sns
import matplotlib.pyplot as plt
sample_df = df_cleaned.sample(n=1000, random_state=42)

sns.set_theme(style="whitegrid")
plt.figure(figsize=(10, 8))

sns.scatterplot(
    data=sample_df,
    x='valence',
    y='energy',
    alpha=0.3,   
    s=20,        
    color='teal',
    edgecolor=None)
plt.axvline(0.5, color='red', linestyle='--', linewidth=1.5, alpha=0.7, label='Decision boundary 0.5')
plt.axhline(0.5, color='red', linestyle='--', linewidth=1.5, alpha=0.7)

plt.title('Valence vs Energy Distribution', fontsize=16, fontweight='bold', pad=15)
plt.xlabel('Valence', fontsize=12)
plt.ylabel('Energy', fontsize=12)
plt.legend()
plt.tight_layout()

plt.savefig('raw_2d_scatter.png')
plt.close()

In [29]:
# Save the DataFrame to a CSV file
df_cleaned.to_csv('cleaned_data.csv', index=False)